let discoveryData={rows:[],analyzed:0,catalogRead:0,catalogTotal:null},discoveryBusy=false,discoveryError='',discoveryNext=0,discoverySerial=0,discoveryFilter='';
function discoveryQuery(){const p=ideaPreferences();return new URLSearchParams({mode:p.mode,window:p.window,minimum:String(p.minimum),ceiling:String(p.ceiling)}).toString();}
async function fetchDiscovery(force=false){
  if(currentPage!=='ideas'||document.hidden||!window.location?.protocol?.startsWith('http')||!force&&(discoveryBusy||Date.now()<discoveryNext))return;
  const serial=++discoverySerial,query=discoveryQuery();discoveryBusy=true;discoveryError='';
  if($('#ideas-results'))$('#ideas-results').innerHTML=ideaResults();
  try{
    const response=await fetch(`/api/discovery?${query}`,{cache:'no-store'});
    let data;try{data=await response.json();}catch(_){throw Error(response.status===504?'La scansione ha impiegato troppo tempo. Riprova: l’avanzamento salvato viene conservato.':'Il server non ha restituito i dati della ricerca. Ricarica la pagina o riprova.');}
    if(serial!==discoverySerial)return;
    if(!response.ok)throw Error(data.error||'Ricerca non disponibile.');
    discoveryData=data;discoveryFilter=query;discoveryNext=Date.now()+(data.retryAfter||65)*1000;
    for(const row of [...(data.rows||[]),...(data.previewRows||[])])if(row.asset)catalogueAssets.set(row.symbol,row.asset);
  }catch(error){if(serial===discoverySerial){discoveryError=error.message;discoveryNext=Date.now()+65000;}}
  finally{if(serial===discoverySerial){discoveryBusy=false;if($('#ideas-results'))$('#ideas-results').innerHTML=ideaResults();}}
}
function ideaPreferences() {
  const p = state.ideaPreferences || {};
  return { mode:['drops','cheap','recovery'].includes(p.mode)?p.mode:'drops', window:p.window==='quarter'?'quarter':'year', minimum:[10,20,40,60].includes(p.minimum)?p.minimum:20, ceiling:[5,10,25,50,100].includes(p.ceiling)?p.ceiling:25, includeOwned:!!p.includeOwned, diversify:!!p.diversify };
}
function ideaContext() {
  const positions = holdings(), groups = new Map(), total = positions.reduce((s,h)=>s+h.value,0);
  for (const h of positions) { const group=company(h.ticker,h.name).group; if(group && group!=='Altro') groups.set(group,(groups.get(group)||0)+h.value); }
  const dominant = [...groups].sort((a,b)=>b[1]-a[1])[0];
  return { owned:positions.map(h=>state.symbols?.[h.ticker]||h.ticker), dominant:dominant?.[0]||'', share:dominant && total?dominant[1]/total*100:0, positions:positions.length };
}
function ideaRows() {
  if(discoveryFilter!==discoveryQuery())return [];
  return (discoveryData.rows||[]).map(r=>({ ...r, group:company(r.symbol).group, kind:r.asset?.kind || 'stocks' }));
}
function renderIdeas() {
  const p = ideaPreferences(), context=ideaContext();
  return `${pageHeading('La tua ricerca personale','Idee per te.','Trova titoli da approfondire in base ai prezzi reali e a ciò che possiedi.',`<button class="button-secondary" data-discovery-refresh>${icon('refresh')} Aggiorna dati</button>`)}
    <section class="panel ideas-intro"><div><span class="section-kicker">Parti dai fatti</span><h2>Un ribasso è un punto di partenza.</h2><p>Qui cerchiamo prezzi bassi, forti discese e recuperi già iniziati. Per capire se un’azienda ha buone prospettive servono anche bilanci, debiti e risultati: questi dati non sono inclusi nella selezione.</p></div><div class="ideas-personal"><span>${icon('wallet')} Dal tuo portafoglio</span><strong>${context.positions ? `${context.positions} titoli posseduti` : 'Ancora nessuna posizione'}</strong><p>${context.dominant ? `${esc(context.dominant)} pesa circa il ${amount(context.share)}% del valore stimato. Puoi dare precedenza ad altri settori.` : 'Escludiamo i titoli già posseduti quando sono riconosciuti tramite il simbolo associato.'}</p><small>Personalizzazione basata su posizioni e filtri, senza valutazione della tua tolleranza al rischio.</small></div></section>
    <section class="panel ideas-filter-panel"><div class="idea-modes" role="group" aria-label="Tipo di idee">${[['drops','down','Forti ribassi','Molto sotto il massimo osservato'],['cheap','wallet','Prezzo basso','Un limite in dollari per azione'],['recovery','activity','Segnali di recupero','Settimana positiva, mese negativo']].map(([id,symbol,title,description])=>`<button data-idea-mode="${id}" aria-pressed="${p.mode===id}" class="${p.mode===id?'active':''}">${icon(symbol)}<span><strong>${title}</strong><small>${description}</small></span></button>`).join('')}</div>
    <div class="idea-filters"><label>Periodo del massimo<select data-idea-pref="window"><option value="year" ${p.window==='year'?'selected':''}>Ultimo anno disponibile</option><option value="quarter" ${p.window==='quarter'?'selected':''}>Ultimi 3 mesi disponibili</option></select></label>${p.mode==='cheap'?`<label>Prezzo massimo per azione<select data-idea-pref="ceiling">${[5,10,25,50,100].map(n=>`<option value="${n}" ${p.ceiling===n?'selected':''}>${n} USD</option>`).join('')}</select></label>`:`<label>Ribasso minimo dal massimo<select data-idea-pref="minimum">${[10,20,40,60].map(n=>`<option value="${n}" ${p.minimum===n?'selected':''}>Almeno ${n}%</option>`).join('')}</select></label>`}<label class="idea-check"><input type="checkbox" data-idea-pref="includeOwned" ${p.includeOwned?'checked':''}>Includi i titoli che possiedo</label><label class="idea-check"><input type="checkbox" data-idea-pref="diversify" ${p.diversify?'checked':''} ${!context.dominant?'disabled':''}>Prima altri settori</label></div><p class="form-hint">${p.mode==='cheap'?'Il prezzo è in USD e riguarda una singola azione: non misura quanto vale o quanto crescerà l’azienda.':p.mode==='recovery'?'Un rialzo negli ultimi 5 giorni di borsa, con gli ultimi 21 ancora negativi: è un movimento già avvenuto, non la previsione di un rimbalzo.':'Ordinate dal ribasso maggiore. Una discesa più forte può riflettere problemi più seri: non indica una maggiore probabilità di risalita.'}</p></section>
    <div id="ideas-results" aria-live="polite">${ideaResults()}</div>
    <details class="panel portfolio-explainer"><summary>Come vengono scelte e ordinate?</summary><p>La ricerca scorre il catalogo USA del provider, indipendentemente dal tuo radar. Esclude ETF e sedi secondarie, analizza lo storico e conserva i risultati fino a 7 giorni. Ogni scheda mostra la data effettiva.</p><p>Usiamo prezzi giornalieri corretti per gli split, senza dividendi. Servono almeno 21 giorni di borsa disponibili. Nei forti ribassi ordiniamo dalla discesa maggiore; nei prezzi bassi dal prezzo minore; nei recuperi dal rialzo settimanale maggiore. “Prima altri settori” mette davanti i settori classificati diversi da quello prevalente nel tuo portafoglio, senza calcolare correlazioni o garantire diversificazione.</p><p>La distanza dal massimo e il rialzo necessario per tornarci sono calcoli storici, non obiettivi di prezzo. Non stimiamo una probabilità di guadagno e non verifichiamo automaticamente utili, debito o valore dell’azienda.</p><div class="form-actions"><a class="button-secondary" href="https://www.finra.org/investors/investing/investment-products/stocks/evaluating-stocks" target="_blank" rel="noopener noreferrer">Come valutare un’azione · FINRA</a><button class="button-secondary" data-discovery-refresh>Continua la ricerca USA</button></div></details>`;
}
function ideaResults() {
  const p=ideaPreferences(), context=ideaContext(), rows=ideaRows();
  const selected=FormaResearch.screenIdeas(rows,{...p,...context}), relevant=selected.slice(0,18);
  const pending=discoveryBusy;
  return `<section class="panel discovery-progress"><div><span class="section-kicker">Ricerca USA indipendente</span><h2>${discoveryData.analyzed||0} titoli analizzati</h2><p>${discoveryData.catalogRead||0} schede del catalogo esplorate${discoveryData.catalogTotal?' su '+amount(discoveryData.catalogTotal):''}. La scansione prosegue oltre i titoli del tuo radar.</p></div><p>${discoveryData.budgetReached?'Budget giornaliero della scansione raggiunto. Riprende al prossimo rinnovo del budget; i risultati raccolti restano disponibili.':pending?'Analisi del prossimo gruppo in corso…':'La ricerca avanza mentre questa pagina resta aperta e riprende dal punto salvato su PC e telefono.'}</p><small>Fino a 6 nuovi titoli ogni 65 secondi. Risultati conservati per 7 giorni, con data su ogni scheda. ${discoveryData.failed||0} richieste senza storico utilizzabile.${discoveryData.retryAt?` Prossimo controllo: ${new Date(discoveryData.retryAt).toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit',second:'2-digit'})}.`:""}</small></section><div class="ideas-result-heading"><div><h2>${selected.length?selected.length+' titoli da approfondire':pending?'Ricerca in corso':discoveryError||discoveryData.error?'Ricerca da riprendere':discoveryData.analyzed?'Nessuna corrispondenza con questi filtri':'In attesa dei primi dati'}</h2><p>Tra i risultati raccolti dal catalogo USA, con i tuoi filtri.${discoveryData.limited?' Mostriamo una selezione dei primi 240 risultati compatibili; restringi le soglie per affinare la ricerca.':''}</p></div><span class="sector-tag">${p.includeOwned?'Include il tuo portafoglio':'Esclude i titoli posseduti'}</span></div>${discoveryError||discoveryData.error?`<p class="inline-warning">${esc(discoveryError||discoveryData.error)}</p>`:''}${relevant.length?`<div class="research-ideas-grid">${relevant.map(r=>ideaCard(r,p)).join('')}</div>${selected.length>18?'<p class="form-hint">Mostriamo i primi 18 risultati. Usa i filtri per restringere la ricerca.</p>':''}`:`<section class="panel empty-state"><div class="empty-icon">${icon('compass')}</div><h3>${discoveryData.analyzed?'Nessun risultato nei titoli analizzati con questi filtri.':'La ricerca sta iniziando dal catalogo USA.'}</h3><p>${pending?'Analisi in corso…':'La scansione continua a esplorare nuove aziende. Puoi cambiare categoria o soglie; i progressi restano salvati.'}</p><button class="button-secondary" data-discovery-refresh ${pending?'disabled':''}>${icon('refresh')}${pending?'Analisi in corso…':'Continua ricerca'}</button><button class="button-subtle" data-discovery-relax>Allenta i filtri</button></section>${discoveryPreview()}`}`;

}
function ideaCard(r,p) {
  const c=company(r.symbol), reason=p.mode==='cheap'?`Prezzo entro ${p.ceiling} USD`:p.mode==='recovery'?'Recupero negli ultimi 5 giorni di borsa':`Almeno ${p.minimum}% sotto il massimo osservato`;
  const stale=Date.now()-Number(r.fetchedAt)>2*60*60_000;
  const name=esc(c.name), stat=r.stats;
  return `<article class="panel research-idea"><div class="idea-top"><span class="idea-label">${icon(p.mode==='cheap'?'wallet':p.mode==='recovery'?'activity':'down')}${esc(reason)}</span><button class="bookmark-button ${state.watchlist.includes(r.symbol)?'saved':''}" data-bookmark="${esc(r.symbol)}" aria-label="Salva o rimuovi ${name}" aria-pressed="${state.watchlist.includes(r.symbol)}">${icon('bookmark')}</button></div><div class="idea-company"><span class="ticker-logo ${c.hue}">${esc(c.symbol.slice(0,4))}</span><div><h3>${name}</h3><span>${esc(c.symbol)} · ${esc(c.sector)}${r.owned?' · Già in portafoglio':''}</span></div></div><div class="research-numbers"><div><span>Ultimo prezzo</span><strong>${marketPrice(r)}</strong></div><div><span>Dal massimo osservato</span><strong class="${tone(stat.drawdown)}">${marketChange(stat.drawdown)}</strong></div></div><div class="idea-evidence"><span>5 giorni di borsa <strong class="${tone(r.week)}">${marketChange(r.week)}</strong></span><span>21 giorni di borsa <strong class="${tone(r.month)}">${marketChange(r.month)}</strong></span></div><p class="research-date">${stat.sessions} giorni di borsa disponibili · ${day(stat.from)} – ${day(stat.to)}<br>Prezzo del ${day(r.date)} · ${esc(r.exchange)}${stale?' · Dati da aggiornare':''}</p>${p.diversify&&r.otherSector?'<p class="research-match">Settore diverso da quello prevalente nel tuo portafoglio.</p>':''}<div class="research-risks"><strong>Cosa controllare</strong><ul>${r.risks.map(text=>`<li>${esc(text)}</li>`).join('')}</ul></div><details class="research-thesis"><summary>Il calcolo del recupero e le prospettive</summary><p>Il massimo osservato è ${marketPrice({price:stat.high,currency:r.currency})}. Per tornarci dal prezzo attuale servirebbe ${percentage(r.recoveryToHigh)}. È un calcolo matematico: non è un obiettivo, una previsione o una probabilità.</p><p><strong>Prospettive non ancora valutate.</strong> Prima di decidere, verifica crescita di ricavi e utili, cassa rispetto ai debiti, emissione di nuove azioni e il motivo del ribasso. Annota quale fatto potrebbe favorire un recupero e quale smentirebbe la tua tesi.</p>${c.url?`<a href="${esc(c.url)}" target="_blank" rel="noopener noreferrer">Leggi i documenti dell’azienda</a>`:'<p>Cerca gli ultimi risultati sul sito ufficiale dell’azienda.</p>'}</details><div class="research-actions"><button class="button-primary" data-open-chart="${esc(r.symbol)}">Guarda il grafico ${icon('arrow')}</button><button class="button-secondary" data-note="${esc(r.symbol)}">Scrivi la tua tesi</button></div><small class="research-source">Fonte: Twelve Data · Prezzi e volumi, senza analisi dei bilanci</small></article>`;
}
function saveIdeaPreference(key,value) { state.ideaPreferences={...ideaPreferences(),[key]:value}; save(); render(); fetchDiscovery(true); }
document.addEventListener('click',event=>{const mode=event.target.closest('[data-idea-mode]');if(mode)saveIdeaPreference('mode',mode.dataset.ideaMode);});
document.addEventListener('change',event=>{
  const key=event.target.dataset?.ideaPref;if(!key)return;
  const value=event.target.type==='checkbox'?event.target.checked:['ceiling','minimum'].includes(key)?Number(event.target.value):event.target.value;
  saveIdeaPreference(key,value);
});

document.addEventListener('click',event=>{if(event.target.closest('[data-discovery-refresh]'))fetchDiscovery(true);});
setInterval(()=>fetchDiscovery(),15000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden)fetchDiscovery();});

function discoveryPreview(){
 const rows=discoveryData.previewRows||[];if(!rows.length)return '';
 return `<details class="panel portfolio-explainer"><summary>Titoli analizzati fuori dai filtri (${rows.length})</summary><p>Questi titoli hanno dati disponibili, ma possono non rispettare i criteri scelti. Puoi controllarli e decidere se modificare i filtri.</p><div class="discovery-preview">${rows.map(r=>`<div><span>${esc(r.asset?.name||r.name||r.symbol)}<small>${esc(r.asset?.symbol||r.symbol)} / ${marketStamp(r)}</small></span><strong>${marketPrice(r)}</strong><button class="button-secondary" data-open-chart="${esc(r.symbol)}">Apri grafico</button></div>`).join('')}</div></details>`;
}
document.addEventListener('click',event=>{if(event.target.closest('[data-discovery-relax]')){state.ideaPreferences={...ideaPreferences(),minimum:10,ceiling:50};save();render();fetchDiscovery(true);}});
